### ISSUE TITLE
Add way to link into product page features

### ISSUE THREAD

**Issue by agjohnson** [readthedocs/website#11]
Thinking about this a bit, we probably want a want to link into our product page for each feature. For example, our pricing page might link into a specific feature for more details on the feature. Or some landing page might call out to a specific feature we should link the reader back to.

The obvious option would be to highlight the card, there are border styling for segments that I think also work on cards. There might be a case for a more specific feature here however, like collapsing/muting/disabling other cards or something similar.

**Comment by nienn** [comment]
The highlight option is good. I like it more than disabling other cards (that can more easily lead to misunderstandings, especially if the highlighted URL is taken out of context - ex: shared).

We might also want templates to show each feature separately. If we don't want to maintain the information in 2 places than we can use the same code via `import` and just showing it a separate page, free from the surrounding _noise_, This would also pave the way to expanding on some specific feature that in future we may decide its worth the extra effort.

**Comment by agjohnson** [comment]
Yeah, separating the cards by template includes seems like a good idea either way. Highlight seems like a good option for now though.

One small hurdle that would be good to discuss at some point before we get deep into JS would be options for routing in JS. I struggled to find a great solution here on the application templates so far. I'll open a discussion there, as we'll probably want to figure out a pattern soon, and avoid and inline scripts.

**Comment by agjohnson** [comment]
This is maybe old, but either way I think the plan here I favor more is to have more specific pages on features that we link to. This would involve trimming some marketing content from our docs too, which is a win. We'd consolidate more feature marketing content on these pages.

I'm going to close this as this is more specific to linking to the existing overview page.
