### ISSUE TITLE
Pricing Page: Add button to expand/collapse the features list

### ISSUE THREAD

**Issue by nienn** [readthedocs/website#12]
From discussion at https://github.com/readthedocs/site-community/pull/4#pullrequestreview-820825384.

We also brainstormed a bit more on this later. The idea was to turn the current proposed full list of features in the pricing tables scheme into **Option 1** as detailed in https://github.com/readthedocs/site-community/pull/4#discussion_r761202710 (**the "All that's included in previous plan, plus..." option**) and add a button near the top to expand the complete list of features - effectively turning it into **Option 2** again but this time only by explicit user request.

**Comment by agjohnson** [comment]
I added a full on table of features to the pricing page a while ago, which I think supersedes this issue.
