### ISSUE TITLE
Rename repo

### ISSUE THREAD

**Issue by agjohnson** [readthedocs/website#162]
We have matured the concept of our website since this repo started and it's to the point now where this repo is less "our community site" and is more "our website". When I refer to this project, I call this our "website", instead of "landing pages" and "site-community".

It seems like a good time to rename this repo, before we start using it more heavily. I'm suggesting "readthedocs/website".

**Comment by humitos** [comment]
> I'm suggesting "readthedocs/website".

Sounds good to me! 👍🏼

**Comment by ericholscher** [comment]
Yea, `website` sounds good, and makes the most since for users. Though we have a lot of "websites" so it is not 100% explicit internally unless we standardize on it.

**Comment by agjohnson** [comment]
I finally made good on this one. The GitHub redirect looks good, but feel free to update your remotes. I'll close with a PR with some text updates next
