### ISSUE TITLE
https://readthedocs.org/sustainability/

### ISSUE THREAD

**Issue by silopolis** [readthedocs/website#178]
Hi,

After spending part of the day translating the website into French on Transifex and then "reviewing" it quickly, it seems to me that there is a problem with https://readthedocs.org/sustainability/ page:

* It only has two translated strings, but the others can't be found in translation resource
* Numbers of projects and users are not the same (much bigger) than on the home page

If this could be solved, I'd be glad to complete this translation :)

**Comment by agjohnson** [comment]
We likely won't keep this page for much longer, at least not in it's current form. This may turn into something else at some point, we're not really seeking donations at the moment though. I'd probably say we can skip translating this page, as it's copy heavy and will likely go away or change significantly at some point.

**Comment by silopolis** [comment]
I leave you to close this issue if you really think there's no point in
translating it :)

**Comment by agjohnson** [comment]
Noted on chat, but at least one other page that could stand to be translated would the support template:

https://github.com/readthedocs/readthedocs.org/blob/main/readthedocs/templates/support/index.html

There are likely a few other pages too.

**Comment by humitos** [comment]
We deleted the original page and now it redirects to https://about.readthedocs.com/pricing/#/community
