### ISSUE TITLE
Marketing plan to promote MkDocs more

### ISSUE THREAD

**Issue by humitos** [readthedocs/website#218]
Today I talked to Eric about MkDocs and Material for MkDocs and we thought it would be pretty good to promote them more in our platform. Currently, I'd say that most people knows that Read the Docs works _flawlessly_ 😉 with Sphinx but not many people know it works in the same way with MkDocs.

I'm opening this issue to figure it out and define a marketing plan to change this and let people know about how to use MkDocs in our platform in the same way they can use Sphinx.

Some ideas that I remember that Eric mentioned in our talk:

* create a landing page (similar to https://about.readthedocs.com/tools/sphinx/)
* create an example project for Material for MkDocs
* how to guide
* mention MkDocs at import time

I'm assigning this issue to Eric because he has more clear ideas about this to write them down here. That way, we can start prioritizing this work and moving forward.

**Comment by humitos** [comment]
We have a landing page for MkDocs already at https://about.readthedocs.com/tools/mkdocs/

**Comment by ericholscher** [comment]
Yea, it's actually getting a decent amount of traffic, mostly from Google! https://plausible.io/about.readthedocs.com?page=%2Ftools%2Fmkdocs%2F

**Comment by ericholscher** [comment]
<img width="1101" alt="Screenshot 2023-11-07 at 1 15 29 PM" src="https://github.com/readthedocs/website/assets/25510/9e018aac-156f-49ff-be44-b34dd21424af">

**Comment by ericholscher** [comment]
<img width="1092" alt="Screenshot 2023-11-07 at 1 15 56 PM" src="https://github.com/readthedocs/website/assets/25510/1d01d4e5-e5e2-4ef8-94f8-5b8afe6b10b5">

**Comment by humitos** [comment]
I followed the "Getting started with MkDocs" guide that we have at https://docs.readthedocs.io/en/latest/intro/getting-started-with-mkdocs.html and ended up a little frustrated 🥲 . I opened a discussion at https://github.com/readthedocs/meta/discussions/136 with my findings and with some proposed work towards a potential solution.

I think the work I've done there would be useful to "split the onboarding process" in the future when we want to promote more doctools than Sphinx and MkDocs.

**Comment by humitos** [comment]
The work required for this issue is already done. We have a MkDocs landing page, so I think we can close it.

We can continue the discussion about "Getting started with MkDocs" in the linked meta discussion.
