### ISSUE TITLE
Post: write a blog post about the offsite 2024

### ISSUE THREAD

**Issue by humitos** [readthedocs/website#294]
I'd be really cool to write a small blog post about the offsite 2024, similar to what we wrote in https://blog.readthedocs.com/offsite-2019/

**Comment by ericholscher** [comment]
Goal:

* Post a photo
* Talk about the high-level roadmap planning

**Comment by agjohnson** [comment]
Pruning backlog, seems like we're far enough past the offsite we could close this? Newsletter updates and our end of year post feel like where we have/can discuss vision.
