### ISSUE TITLE
Home page: describe "the rest"

### ISSUE THREAD

**Issue by agjohnson** [readthedocs/website#30]
In https://github.com/readthedocs/site-community/pull/23#discussion_r782340583 we discussed keeping the header copy short and vague, but also recognized we might be *too* vague with the copy.

The copy we're describing is "Push your docs, we'll do the rest". We don't describe everything that we do however, so "the rest" is a bit too vague and hand wavy magic.

We should come back to this and provide the user with more context here.

**Comment by agjohnson** [comment]
One options could be to retain the header, and provide an enumeration of the things that RTD does -- "the rest". Maybe in a header styled bullet list of sorts. This provides the context to the user about what we're describing when we say "the rest".

**Comment by astrojuanlu** [comment]
Also: rework "it just works"/"get your docs online in 5 minutes".
