### ISSUE TITLE
Write page for "Other / Generic" support tool

### ISSUE THREAD

**Issue by humitos** [readthedocs/website#301]
We are promoting Sphinx, MkDocs and Jupyter Book as the only _Supported tools_ in our main website. However, we support more tools than those ones. I propose to write a _"Generic tool"_ page to explain this use case is also supported.

![Screenshot_2024-06-21_13-50-57](https://github.com/readthedocs/website/assets/244656/d050811a-88e2-4a93-a9eb-ce83fad56002)

I think potential customers that are using a different doctool won't sign up if they see here that we don't support other doctools.

**Comment by agjohnson** [comment]
Noting this could be Markdoc support too, maybe a individual page eventually. Docusaurus as well

**Comment by ericholscher** [comment]
I added #336  for Markdoc and #337 for generic tool.
