### ISSUE TITLE
Graphic design: Create 3 illustrations for the product #user-segments

### ISSUE THREAD

**Issue by nienn** [readthedocs/website#36]
Create 3 illustrations for the `product` page.

These illustrations can to added before the `<h3>` in each `.column` of the `#user-segments` section and should illustrate a feature of read the docs that appeals particularly to each one of those segments.

```html
<div class="column">
  <div>
    <img class="ui fluid image" src="" />
    <h3 class="ui header inverted">Header</h3>
    ...
```

**Comment by agjohnson** [comment]
This section was dropped from our product page so this isn't wholly necessary. If we add new pages for these subproducts, we'll mostly be using font awesome to supply the graphic elements.
