### ISSUE TITLE
CSS: add custom styling to the blog home page

### ISSUE THREAD

**Issue by nienn** [readthedocs/website#61]
The blog homepage is currently very dull and could use some cheerful styling!

There are also some issues with the Semantic UI styling of the `a.card` inheriting from `a{text-decoration:underline}`.
Additionally, the behaviour of the multiple cards with different heights should be checked and adjusted.

* _Edit: partially fixed in PR #69 which solves the issue with the `a.card` styling._

**Comment by agjohnson** [comment]
I recently updated some of the layout here, but in the end this will be a grid of posts so the content will fill out nicely. We still haven't made changes to our author patterns due to our newsletter.
